@extends('layouts.adminui')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        View Generated Reports
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
        	<div class="box">
            <div class="box-header">
              <h3 class="box-title">List of Generated Reports by All Users</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="reportsTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Id</th>
                  <th>Report Generated By</th>
                  <th>Report Of</th>
                  <th>Report Generation Date</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                  <?php
                    $aViolatorList = [];
                    foreach ($aViolators as $aTempViolator) {
                      if ($aTempViolator->violator_mname === 'N/A') {
                        $aTempViolator->violator_mname = '';
                      }
                      $aViolatorList[$aTempViolator->violator_id] = $aTempViolator->violator_lname . ', ' . $aTempViolator->violator_fname . ' ' . $aTempViolator->violator_mname;
                    }

                    $aUsersList = [];
                    foreach ($aUsers as $aTempUsers) {
                      $aUsersList[$aTempUsers->account_id] = $aTempUsers->user_lname . ', ' . $aTempUsers->user_fname;
                    }
                  ?>
                  <?php
                    foreach ($aReports as $aReport) {
                  ?>
                  <tr>
                    <td><?=$aReport->report_id?></td>
                    <td><?=$aUsersList[$aReport->account_id]?></td>
                    <td><?=$aViolatorList[$aReport->violator_id]?></td>
                    <td><?=date('Y/m/d', $aReport->report_date)?></td>
                    <td><button type="button" onclick="downloadReport('<?=$aReport->report_path?>')" class="btn btn-block btn-success" >Download Report</button></td>
                  </tr>
                  <?php
                    }
                  ?>
                </tbody>
                <tfoot>
                <tr>
                  <th>Id</th>
                  <th>Report Generated By</th>
                  <th>Report Of</th>
                  <th>Report Generation Date</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection
@section('localjs')
<script src="{{ url('/') }}/js/jquery.dataTables.min.js"></script>
<script src="{{ url('/') }}/js/dataTables.bootstrap.min.js"></script>
<script src="{{ url('/') }}/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script type="text/javascript">
    $('#reportsTable').DataTable({
        "order": [[ 0, "desc" ]]
    });
    function downloadReport(sPath) {
      window.open(`{{ url("/") }}${sPath}`,'_blank');
    }
</script>
@endsection